services:
  # node management
  node-management:
    build: .
    image: conflux/confura:latest
    command: nm --cfx
    ports:
      - 22530:22530
    restart: unless-stopped
    depends_on:
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-node-management

  ethnode-management:
    image: conflux/confura:latest
    command: nm --eth
    ports:
      - 28530:28530
    restart: unless-stopped
    depends_on:
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-ethnode-management

  # blockchain sync
  chain-sync:
    image: conflux/confura:latest
    command: sync --db
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_STORE_MYSQL_ENABLED=true
      - INFURA_STORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_cfx?parseTime=true
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-sync

  ethchain-sync:
    image: conflux/confura:latest
    command: sync --eth
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_ETHSTORE_MYSQL_ENABLED=true
      - INFURA_ETHSTORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_eth?parseTime=true
      - INFURA_SYNC_ETH_FROMBLOCK=36935000
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-ethsync

  # virtual filter
  virtual-filter:
    image: conflux/confura:latest
    command: vf --cfx
    ports:
      - "42537:42537"
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_STORE_MYSQL_ENABLED=true
      - INFURA_STORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_cfx?parseTime=true
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-virtual-filter

  ethvirtual-filter:
    image: conflux/confura:latest
    command: vf --eth
    ports:
      - "48545:48545"
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_ETHSTORE_MYSQL_ENABLED=true
      - INFURA_ETHSTORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_eth?parseTime=true
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-ethvirtual-filter

  # rpc proxy
  rpc-proxy:
    image: conflux/confura:latest
    command: rpc --cfx
    ports:
      - "22537:22537"
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
      - node-management
      - virtual-filter
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_STORE_MYSQL_ENABLED=true
      - INFURA_STORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_cfx?parseTime=true
      - INFURA_NODE_ROUTER_NODERPCURL=http://node-management:22530
      - INFURA_VIRTUALFILTERS_CLIENT_ENABLED=true
      - INFURA_VIRTUALFILTERS_CLIENT_SERVICERPCURL=http://virtual-filter:42537
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-rpc

  ethrpc-proxy:
    image: conflux/confura:latest
    command: rpc --eth
    ports:
      - "28545:28545"
    restart: unless-stopped
    depends_on:
      - db
      - influxdb
      - ethnode-management
      - ethvirtual-filter
    env_file:
      - path: .env
        required: false
    environment:
      - INFURA_STORE_MYSQL_ENABLED=true
      - INFURA_STORE_MYSQL_DSN=root:root@tcp(db:3306)/confura_eth?parseTime=true
      - INFURA_NODE_ROUTER_ETHNODERPCURL=http://ethnode-management:28530
      - INFURA_ETHVIRTUALFILTERS_CLIENT_ENABLED=true
      - INFURA_ETHVIRTUALFILTERS_CLIENT_SERVICERPCURL=http://ethvirtual-filter:48545
      - INFURA_METRICS_ENABLED=true
      - INFURA_METRICS_INFLUXDB_HOST=http://influxdb:8086
      - INFURA_METRICS_INFLUXDB_DB=confura_testnet
    container_name: confura-ethrpc

  # middlewares
  db:
    image: mysql:8
    ports:
      - "3306"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
    container_name: confura-database

  influxdb:
    image: influxdb:1.8-alpine
    platform: linux/amd64
    ports:
      - "8086"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - INFLUXDB_DB=confura_testnet
    volumes:
      - influxdb-data:/var/lib/influxdb
    container_name: confura-influxdb

  grafana:
    image: grafana/grafana:11.2.2
    platform: linux/amd64
    ports:
      - "3000"
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - grafana-data:/var/lib/grafana
    container_name: confura-grafana

# others
networks:
  default:
    name: confura-internal

volumes:
  db-data: {}
  influxdb-data: {}
  grafana-data: {}