{
 "title": "Node Management RED",
 "tags": [
  "red",
  "node",
  "route",
  "management"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "influxdb" },
   { "name": "space", "label": "Space", "query": "cfx,eth" },
   { "name": "routeGroup", "label": "RouteGroup", "query": "show measurements" },
   { "name": "routeQps", "query": "show measurements" },
   { "name": "nodeAvailabilty", "query": "show measurements" },
   { "name": "rate", "label": "Rate", "query": "m1,m5,m15" },
   { "name": "latency", "label": "Latency", "query": "mean, p50, p75, p95, p99, max" },
   { "name": "nodeLatency", "query": "show measurements" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\nThis dashboard follows the RED method (Rate of traffic, Errors, Duration/latency) to measure node management service.\n\n- The \"Network\" variable is the data source for the dashboard, and it applies to the whole dashboard.\n- The \"Space\" variable is the network space and \"RouteGroup\" is the node goup, they are used to filter nodes to show.\n- The \"Rate\" variable only applies to the rate breakdown, and the \"Latency\" variable only applies to the duration breakdown."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate (aka Traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Route QPS for $space space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$routeQps$/",
     "select": [
      [
       { "params": [ "$rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node availability for $space space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$nodeAvailabilty$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration (aka Latency)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node heartbeat latency for $space space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$nodeLatency$/",
     "select": [
      [
       { "params": [ "$latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}