{
 "title": "Sync Fullnode Query",
 "tags": [
  "sync",
  "fullnode",
  "drilldown"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "influxdb" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard follows the RED method (Rate of traffic, Errors, Duration/latency) to measure fullnode query status for sync service. TODO: instrument failure query rate/latency \n\n- The \"Network\" variable is the data source for the dashboard, and applies to the whole dashboard. "
   }
  },
  { "title": "Rate (aka Traffic)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Epoch query QPS for CFX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/cfx/fullnode.timer",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block query QPS for ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/eth/fullnode.timer",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fullnode query availability by space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "cfx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/cfx/fullnode/availability.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "eth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/eth/fullnode/availability.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Duration (aka Latency)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Epoch query latency for CFX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/cfx/fullnode.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Block query latency for ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/eth/fullnode.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}