{
 "title": "Sync RED",
 "tags": [
  "sync",
  "RED"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "influxdb" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard follows the RED method (Rate of traffic, Errors, Duration/latency) to measure sync service from high level perspective. TODO: split by sync type (eg., db sync, kv sync)\n\n- The \"Network\" variable is the data source for the dashboard, and applies to the whole dashboard. "
   }
  },
  { "title": "Rate (aka Traffic)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Success QPS  for CFX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/cfx/db/once/success.timer",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success QPS for ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "infura/sync/eth/db/once/success.timer",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failure QPS for CFX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/cfx/db/once/failure.timer",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m1" ], "type": "alias" }
        ],
        [
         { "params": [ "m5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m5" ], "type": "alias" }
        ],
        [
         { "params": [ "m15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m15" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failure QPS for ETH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/eth/db/once/failure.timer",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m1" ], "type": "alias" }
        ],
        [
         { "params": [ "m5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m5" ], "type": "alias" }
        ],
        [
         { "params": [ "m15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "m15" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Duration (aka Latency)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success latency  for CFX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/cfx/db/once/success.timer",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Success latency  for ETH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/eth/db/once/success.timer",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failure latency  for CFX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/cfx/db/once/failure.timer",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failure latency  for ETH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/eth/db/once/failure.timer",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch epochs for CFX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/cfx/db/once/size.histogram",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Batch blocks for ETH",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "infura/sync/eth/db/once/size.histogram",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mean" ], "type": "alias" }
        ],
        [
         { "params": [ "p75" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p75" ], "type": "alias" }
        ],
        [
         { "params": [ "p95" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p95" ], "type": "alias" }
        ],
        [
         { "params": [ "p99" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "p99" ], "type": "alias" }
        ],
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}