{
 "title": "Virtual Filter",
 "tags": [ "filter API" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "influxdb" },
   { "name": "space", "label": "Space", "query": "cfx,eth" },
   { "name": "node", "label": "Node", "query": "show measurements" },
   { "name": "store", "label": "Store", "query": "memory,mysql" },
   { "name": "sessionMetrics", "query": "show measurements" },
   { "name": "persistQpsMetrics", "query": "show measurements" },
   { "name": "queryQpsMetrics", "query": "show measurements" },
   { "name": "pollQpsMetrics", "query": "show measurements" },
   { "name": "pollSizeMetrics", "query": "show measurements" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard measures the virtual filter sessions delegated to some specific fullnode. It also measures the QPS/latency/size for filter change polling or performance metrics on store operations."
   }
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": " Filter API Sessions to  node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "$m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$sessionMetrics$/",
     "query": "SELECT mean(\"value\") FROM /^$sessionMetrics$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Polling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Poll QPS from node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$pollQpsMetrics$/",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poll latency for node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$pollQpsMetrics$/",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batch logs size polled from node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$pollSizeMetrics$/",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Persistence QPS  to ${store} for node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$persistQpsMetrics$/",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Persistence latency  to ${store} for node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$persistQpsMetrics$/",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query QPS  from ${store} for node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$queryQpsMetrics$/",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m1" ], "type": "alias" }
      ],
      [
       { "params": [ "m5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m5" ], "type": "alias" }
      ],
      [
       { "params": [ "m15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "m15" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query latency  from ${store} for node (${node})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$queryQpsMetrics$/",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ],
      [
       { "params": [ "p75" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p75" ], "type": "alias" }
      ],
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p99" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}